services:
  - type: web
    name: youtube-transcript-api
    runtime: python
    region: frankfurt
    plan: free
    branch: main
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
        
  - type: static
    name: youtube-transcript
    runtime: static
    region: frankfurt
    plan: free
    branch: main
    buildCommand: echo "Frontend ready"
    publishPath: public
    autoDeploy: true
